---

- name: Create docker service override directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    recurse: true
  when:
    - not skip_docker_service_override

- name: Install docker override file
  template:
    src: override.conf.j2
    dest: override_file_1
    backup: false
    owner: root
    group: root
    mode: 0644
  when:
    - (not skip_docker_service_override) and inventory_hostname == groups['docker_swarm_manager'][0]

- name: Install docker override file
  template:
    src: override.conf2.j2
    dest: override_file_2
    backup: false
    owner: root
    group: root
    mode: 0644
  when:
    - (not skip_docker_service_override) and inventory_hostname == groups['docker_swarm_worker'][0]

- name: Reload systemd daemon and restart Docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: true
  when:
    - not skip_docker_restart
