---
language: python
services:
  - docker

install:
  - pip install ansible ansible-lint
  - ansible-lint --version
  - python3 -m pip install "molecule[ansible]"
  - python3 -m pip install "molecule[docker]"

script:
  - ansible-lint .

before_script: cd ./roles/install_docker
script:
  - molecule test
