---
language: generic

dist: xenial

os:
  - linux

install:
  - pip install yamllint
  - pip install ansible-lint

script:
  #- yamllint --no-warnings .
  - ansible-lint -x package-latest /main.yml
   --exclude roles/ansible-dockerswarm-master
