---
- name: Check and Setting on CentOs
  hosts: Servers
  become_user: root
  become: true

  roles:
    - control_storage
    - install_docker
    - ports_opener
    - ansible-role-docker-tls-master
    - ansible-dockerswarm-master
