---
# open ports on CentOS

- name: start firewalld
  command: sudo systemctl start firewalld
  register: start_firewalld
  changed_when: false

- name: enable firewalld
  command: sudo systemctl enable firewalld
  register: enable_firewalld
  changed_when: false

- name: open ports needed
  command: 'sudo firewall-cmd --add-port={{ docker_swarm_port_TCP_client }}/tcp --permanen'
  register: open_2376
  changed_when: false

- name: open ports needed
  command: 'sudo firewall-cmd --add-port={{ docker_swarm_port_TCP_cluster_managment }}/tcp --permanent'
  register: open_2377
  changed_when: false

- name: open ports needed
  command: 'firewall-cmd --add-port={{ docker_swarm_port_TCP_UDP_nodes_communication }}/tcp --permanent'
  register: open_7946_tcp
  changed_when: false

- name: open ports needed
  command: 'firewall-cmd --add-port={{ docker_swarm_port_TCP_UDP_nodes_communication }}/udp --permanent'
  register: open_7946_udp
  changed_when: false

- name: open ports needed
  command: 'firewall-cmd --add-port={{ docker_swarm_port_UDP_overlay_network_traffic }}/udp --permanent'
  register: open_4789
  changed_when: false

- name: reload firewalld
  command: firewall-cmd --reload
  register: reload_firewalld
  changed_when: false

- name: reload system
  ansible.builtin.systemd:
    state: restarted
    name: docker
