---
- name: Install yum utils
  yum:
    name: yum-utils
    state: latest

- name: Install device-mapper-persistent-data
  yum:
    name: device-mapper-persistent-data
    state: latest

- name: Install lvm2
  yum:
    name: lvm2
    state: latest

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  become: true

- name: Enable Docker Edge repo
  ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    mode: 0644
    section: 'docker-ce-edge'
    option: enabled
    value: 0
  become: true

- name: Enable Docker Test repo
  ini_file:
    dest: /etc/yum.repos.d/docer-ce.repo
    mode: 0644
    section: 'docker-ce-test'
    option: enabled
    value: 0
  become: true

- name: Install Docker
  package:
    name: docker-ce
    state: latest
  become: true

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: true
  become: true

- name: Add user vagrant to docker group
  user:
    name: vagrant
    groups: docker
    append: true
  become: true
