---
- name: test to control the disk space
  assert:
    that:
      - not {{ item.mount != '/' or ( item.size_available >  desidered_memory ) }}
  loop: '{{ ansible_mounts|flatten(levels=1) }}'
  ignore_errors: true
  register: sufficient_memory

- name: install lvm2 tools
  package:
    name:
      - lvm2
    state: present
  register: rpm_lvm2_present
  when: sufficient_memory is failed
  

- name: Resize '/dev/sda1' device in order to have 40 GB
  command: fsadm -y resize {{ disposive_loc }} {{ desidered_memory }}
  when: sufficient_memory is failed
