---
- name: test to control the disk space
  assert:
    that:
      - " {{ item.mount == '/' and ( item.size_available < 42949672960 ) }} "
  loop: "{{ ansible_mounts|flatten(levels=1) }}"
  ignore_errors: true
  register: sufficient_memory

- name: install lvm2 tools
  package:
    name:
      - lvm2
    state: present
  when: sufficient_memory is failed

- name: Resize '/dev/sda1' device in order to have 40 GB
  command: fsadm -y resize '/dev/sda1' 40G
  when: sufficient_memory is failed
